_target_: datasets.dataset.FairnessDataModule
split_dir: splits/ham10000
data_dir: /mnt/HAM10000/
sensitive_attribute: Age
dataset_name: Ham10000
batch_size: 256
num_workers: 10
pin_memory: True
label_noise: 0.15
